name: platform
version: 3.1.0
description: A pluggable, mockable platform abstraction for Dart.
homepage: https://github.com/google/platform.dart

environment:
  sdk: ">=3.3.0-0 <4.0.0"

dependencies:
  meta: ^1.10.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.8
